version: '3.7'

services:
    py3:
        build:
            context: Python3
            args:
                - TIMEZONE
        container_name: py3dev
        image: py3local
        volumes:
            - type: bind
              source: "${HOME}${USERPROFILE}"
              target: /home
    c7:
        build:
            context: CentOS7
            args:
                - TIMEZONE
        container_name: c7dev
        image: c7local
        privileged: true
        volumes:
            - type: bind
              source: "${HOME}${USERPROFILE}"
              target: /home
            - type: bind
              source: /sys/fs/cgroup
              target: /sys/fs/cgroup
              read_only: true
